import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'


export default function About() {
  return <>
    <Head>
      <title>About page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
    <Navbar />
    <Hero eyebrow="About Us" eyebrowColor="eyebrow-purple" tab1="Design" tab2="Development" tab3="Systems design" subhead="This is a subhead that provides more context for what the page is about" headline="This is an H1 headline for the page" />
    </main>
    </>
}