import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import heroImage from "public/other/other-hero.png";
import Image from 'next/image'
import Button from '@/components/Button'


export default function About() {
  return <>
    <Head>
      <title>About page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
    <Navbar />
    <Hero eyebrow="Other" eyebrowColor="eyebrow-teal" tab1="React" tab2="Creative" tab3="Other" subhead="A new subhead for a different page in this website" headline="This is a new H1 passed in through props" />
    <Image
      className={styles.heroImage}
      src={heroImage}
      alt="test image"
      priority
    />
    <grid>
      <Button type="primary">Primary</Button>
      <Button type="secondary">Secondary</Button>
    </grid>
    </main>
    </>
}